/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppChildComponent {
    }
    interface AppForms {
    }
    interface AppParentComponent {
    }
    interface AppRoot {
    }
    interface AppVideoPlayer {
    }
}
declare global {
    interface HTMLAppChildComponentElement extends Components.AppChildComponent, HTMLStencilElement {
    }
    var HTMLAppChildComponentElement: {
        prototype: HTMLAppChildComponentElement;
        new (): HTMLAppChildComponentElement;
    };
    interface HTMLAppFormsElement extends Components.AppForms, HTMLStencilElement {
    }
    var HTMLAppFormsElement: {
        prototype: HTMLAppFormsElement;
        new (): HTMLAppFormsElement;
    };
    interface HTMLAppParentComponentElement extends Components.AppParentComponent, HTMLStencilElement {
    }
    var HTMLAppParentComponentElement: {
        prototype: HTMLAppParentComponentElement;
        new (): HTMLAppParentComponentElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppVideoPlayerElement extends Components.AppVideoPlayer, HTMLStencilElement {
    }
    var HTMLAppVideoPlayerElement: {
        prototype: HTMLAppVideoPlayerElement;
        new (): HTMLAppVideoPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "app-child-component": HTMLAppChildComponentElement;
        "app-forms": HTMLAppFormsElement;
        "app-parent-component": HTMLAppParentComponentElement;
        "app-root": HTMLAppRootElement;
        "app-video-player": HTMLAppVideoPlayerElement;
    }
}
declare namespace LocalJSX {
    interface AppChildComponent {
    }
    interface AppForms {
    }
    interface AppParentComponent {
    }
    interface AppRoot {
    }
    interface AppVideoPlayer {
    }
    interface IntrinsicElements {
        "app-child-component": AppChildComponent;
        "app-forms": AppForms;
        "app-parent-component": AppParentComponent;
        "app-root": AppRoot;
        "app-video-player": AppVideoPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-child-component": LocalJSX.AppChildComponent & JSXBase.HTMLAttributes<HTMLAppChildComponentElement>;
            "app-forms": LocalJSX.AppForms & JSXBase.HTMLAttributes<HTMLAppFormsElement>;
            "app-parent-component": LocalJSX.AppParentComponent & JSXBase.HTMLAttributes<HTMLAppParentComponentElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-video-player": LocalJSX.AppVideoPlayer & JSXBase.HTMLAttributes<HTMLAppVideoPlayerElement>;
        }
    }
}
